// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config';

export default defineConfig({
  datasource: {
    // Aquí es donde vive ahora la URL para que Migrate y el CLI funcionen
    url: process.env.DATABASE_URL || "postgresql://postgres:educacion@localhost:5432/tiendita?schema=public",
  },
});